VERBOSE: true
GRACEFUL: true
FORCE_DEV: false
ENVIRONMENT: development

# server
PORT: "3001"
HOST: "localhost"
GRPC_PORT: "50001"
GRPC_HOST: "localhost"

# mongodb
DATABASE_NAME: "datawyse"
DATABASE_URI: "mongodb://localhost:27017"

# redis database
REDIS_DB: 1
REDIS_PASSWORD: ""
REDIS_URI: "localhost:6379"

# app
APP_MODE: "release"
SERVICE_NAME: "user"
REQUEST_TIMEOUT: 10
SERVICE_TIMEOUT: 5
DATABASE_TIMEOUT: 5
GRPC_SERVICE_TIMEOUT: 10

# auth server configuration
KEYCLOAK_SERVER: "http://localhost:8080"
KEYCLOAK_REALM: "datawyse"
KEYCLOAK_CLIENT_ID: "datawyse"
KEYCLOAK_CLIENT_SECRET: "jZBf6i1tV4lsSMPwG2tfuDr3KD3U2Cel"
KEYCLOAK_REGISTRATION_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmZTU2MDQ3Ny05ZWNlLTQ2ZTItYjA3My01NzliOGMyMDEyN2QifQ.eyJleHAiOjAsImlhdCI6MTY4ODcwOTU1MSwianRpIjoiMjI5ZWI0ZGYtNDUzNy00ZTkzLWE2ZjQtMTJmZTQxMGU1NjAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kYXRhd3lzZSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvZGF0YXd5c2UiLCJ0eXAiOiJSZWdpc3RyYXRpb25BY2Nlc3NUb2tlbiIsInJlZ2lzdHJhdGlvbl9hdXRoIjoiYXV0aGVudGljYXRlZCJ9.Z3Yq1ooUIkjAmNY68sft3SlOk7gUoF8Sb7m9qhiK7VA"
