VERBOSE: true
GRACEFUL: true
FORCE_DEV: false
ENVIRONMENT: development

# server
PORT: "3001"
HOST: "localhost"
GRPC_PORT: "50001"
GRPC_HOST: "localhost"

# mongodb
DATABASE_NAME: "datawyse"
DATABASE_URI: "mongodb://localhost:27017"

# redis database
REDIS_DB: 1
REDIS_PASSWORD: ""
REDIS_URI: "localhost:6379"

# app
APP_MODE: "release"
SERVICE_NAME: "auth"
REQUEST_TIMEOUT: 10
SERVICE_TIMEOUT: 5
DATABASE_TIMEOUT: 5
APP_VERSION: "0.0.1"
GRPC_SERVICE_TIMEOUT: 10

# auth server configuration
KEYCLOAK_SERVER: "http://localhost:8080"
KEYCLOAK_REALM: "datawyse"
KEYCLOAK_CLIENT_ID: "datawyse"
KEYCLOAK_CLIENT_SECRET: "EXiTEMx2qX3bHRGhW9xX8N16PXCs0ilu"
KEYCLOAK_REGISTRATION_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzZGI1ZjA0My1jNDI3LTRjZTgtOTE5YS1jNjM0NTcxN2Y5MmEifQ.eyJleHAiOjAsImlhdCI6MTY5MjUzMTkxMywianRpIjoiMmQxYjA2NzEtMzY0NC00ZWUwLWIwMzktNzVmZmViMGJlOTc3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9kYXRhd3lzZSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9yZWFsbXMvZGF0YXd5c2UiLCJ0eXAiOiJSZWdpc3RyYXRpb25BY2Nlc3NUb2tlbiIsInJlZ2lzdHJhdGlvbl9hdXRoIjoiYXV0aGVudGljYXRlZCJ9.aJ_z00PIx5IHQZPNzbPuCDrX5l9Ei_NmgGg1V-zR-ug"

# telemetry
COLLECTOR_URL: "localhost:4317"